services:
  web:
    build:
      context: .
      args:
        - DEV=true
    command: ["./entrypoint.sh"]
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine

volumes:
  postgres_data: